### ISSUE TITLE
Not sure what the prblem is, something about the length parameter? 

### ISSUE THREAD

**Issue by grahasc** [theSkyseS/HeightsOfSkyrim#1]
Compiling
(C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Git\ozaiglvq.fyt\Runner\HeightsOfSkyrim): dotnet build --runtime win-x64 "HeightsOfSkyrim.csproj" -c Release
No extra data to consider.
Compiled
Sha 5e75e67f1482489a545cb9a5d2fd6e95db09e010
(): dotnet run --project "C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Git\ozaiglvq.fyt\Runner\HeightsOfSkyrim\HeightsOfSkyrim.csproj" -c Release --runtime win-x64 --no-build check-runnability --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Workspace\Plugins.txt
Running
(): dotnet run --project "C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Git\ozaiglvq.fyt\Runner\HeightsOfSkyrim\HeightsOfSkyrim.csproj" --runtime win-x64 --no-build -c Release run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Users\Gaming-1\Documents\My Games\Synthesis\Data\HeightsOfSkyrim" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Workspace\Plugins.txt --OutputPath "C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Workspace\0 - HeightsOfSkyrim" --PatcherName HeightsOfSkyrim --PersistencePath C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Persistence
Mutagen version: 0.32
Mutagen sha: b9ecd83527de2313df5b1e1b33fab451c4df28b3
Synthesis version: 0.19.4
Synthesis sha: 35e30ef2f0373de308999718f7d55ca10ad8a859
run-patcher --DataFolderPath "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "C:\Users\Gaming-1\Documents\My Games\Synthesis\Data\HeightsOfSkyrim" --GameRelease SkyrimSE --LoadOrderFilePath C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Workspace\Plugins.txt --OutputPath "C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Workspace\0 - HeightsOfSkyrim" --PatcherName HeightsOfSkyrim --PersistencePath C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Persistence
Checking runnability
Checking runnability complete
Prepping state.
Using TextFileSharedFormKeyAllocator allocator
RecordException  => Senna (0133B7:Skyrim.esm<Npc>): Specified argument was out of the range of valid values. (Parameter 'length') System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at Mutagen.Bethesda.Skyrim.Internals.NpcBinaryOverlay.get_NAM5()
   at Mutagen.Bethesda.Skyrim.Internals.NpcSetterTranslationCommon.DeepCopyIn(INpc item, INpcGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.NpcSetterTranslationCommon.DeepCopyIn(IMajorRecord item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimMajorRecordSetterTranslationCommon.DeepCopyIn(ISkyrimMajorRecordInternal item, ISkyrimMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.NpcSetterTranslationCommon.DeepCopyIn(INpcInternal item, INpcGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Skyrim.Internals.NpcSetterTranslationCommon.DeepCopyIn(IMajorRecordInternal item, IMajorRecordGetter rhs, ErrorMaskBuilder errorMask, TranslationCrystal copyMask, Boolean deepCopy)
   at Mutagen.Bethesda.Plugins.Records.Internals.MajorRecordSetterTranslationCommon.DeepCopy(IMajorRecordGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.Plugins.Records.MajorRecordMixIn.DeepCopy(IMajorRecordGetter item, TranslationMask copyMask)
   at Mutagen.Bethesda.OverrideMixIns.GetOrAddAsOverride[TMajor,TMajorGetter](IGroupCommon`1 group, TMajorGetter major)   at Mutagen.Bethesda.OverrideMixIns.GetOrAddAsOverride[TMajor,TMajorGetter](IGroupCommon`1 group, TMajorGetter major)
   at HeightsOfSkyrim.Program.RunPatch(IPatcherState`2 state) in C:\Users\Gaming-1\AppData\Local\Temp\Synthesis\00vcppbq.zro\Git\ozaiglvq.fyt\Runner\HeightsOfSkyrim\Program.cs:line 35
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 94
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 456
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by theSkyseS** [comment]
`Using TextFileSharedFormKeyAllocator allocator`
Go to your profile settings(should be in the top right corner), then find something like FormKey allockation and set it to None

Sorry for the late answer, I rarely check my github and email. Please, for support with Synthesis go to it's Discord server
https://discord.gg/GdKZ3SH
