### ISSUE TITLE
New version of Synthesis Cause Error and Blocking Error message

### ISSUE THREAD

**Issue by KebunteL** [theSkyseS/HeightsOfSkyrim#2]
Program.cs(19,63): error CS1061: 'ILoadOrderGetter<ILoadOrderListingGetter>' does not contain a definition for 'AssertHasMod' and no accessible extension method 'AssertHasMod' accepting a first argument of type 'ILoadOrderGetter<ILoadOrderListingGetter>' could be found (are you missing a using directive or an assembly reference?)
Program.cs(19,63): error CS1061: 'ILoadOrderGetter<ILoadOrderListingGetter>' does not contain a definition for 'AssertHasMod' and no accessible extension method 'AssertHasMod' accepting a first argument of type 'ILoadOrderGetter<ILoadOrderListingGetter>' could be found (are you missing a using directive or an assembly reference?)

**Comment by BrentW89** [comment]
I also get this error with the new synthesis when it use to work:

LibGit2Sharp.LibGit2SharpException: failed to write out file: The handle is invalid.
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath)
   at Synthesis.Bethesda.Execution.GitRepository.CloneRepo.Clone(String repoPath, DirectoryPath localDir) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\GitRepository\CloneRepo.cs:line 17
   at Synthesis.Bethesda.Execution.GitRepository.CheckOrCloneRepo.Check(GetResponse`1 remote, DirectoryPath localDir, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\GitRepository\CheckOrCloneRepo.cs:line 56

**Comment by Kexodus** [comment]
Set Mutagen and Synthesis to "Match" instead of "Profile".

**Comment by theSkyseS** [comment]
[6f7f889](https://github.com/theSkyseS/HeightsOfSkyrim/commit/6f7f889b6910d8897155c240dc7282b693051fcf) should be fixed, completely missed a pull request lol
